# # .github/workflows/release.yml
# name: release

# on:
#   workflow_run:
#     workflows: ["tests"]
#     types:
#       - completed

# jobs:
#   release:
#     name: Semantic Release
#     if: github.event.workflow_run.conclusion == 'success' && (github.event.workflow_run.head_branch == 'dev' || github.event.workflow_run.head_branch == 'main')
#     runs-on: ubuntu-latest

#     env:
#       # npm registry must be set so setup-node can write .npmrc
#       NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
#       GITHUB_TOKEN:     ${{ secrets.GITHUB_TOKEN }}

#     steps:
#       - name: Checkout repo
#         uses: actions/checkout@v4

#       - name: Setup Node.js & pnpm
#         uses: actions/setup-node@v4
#         with:
#           node-version: '22.x'
#           cache: 'pnpm'
#           cache-dependency-path: pnpm-lock.yaml

#       - name: Install pnpm
#         uses: pnpm/action-setup@v4

#       - name: Install dependencies
#         run: pnpm install --frozen-lockfile

#       - name: Build Nuxt‑Apex module
#         run: pnpm run prepack

#       - name: Run semantic-release
#         run: npx semantic-release --no-ci
